In [0]:
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
#without ProviderID and VendorID
Xtrain = pd.read_csv('drive/My Drive/Colab Notebooks/Data/train_data_hhp1.csv')
Xtest= pd.read_csv('drive/My Drive/Colab Notebooks/Data/test_data_hhp1.csv')

#Ytrain=Xtrain['DaysInHospital']
#Ytest=Xtest['DaysInHospital']#, axis=1, inplace=True)


#Xtrain.drop(['DaysInHospital','Year','ClaimsTruncated','MemberID'],axis=1, inplace=True)
#Xtest.drop(['DaysInHospital','Year','ClaimsTruncated','MemberID'],axis=1, inplace=True)

In [0]:
Xtrain['Age_young'] = Xtrain['age_05'] + Xtrain['age_15'] + Xtrain['age_25'] 
+ Xtrain['age_35'] + Xtrain['age_45'] + Xtrain['age_55'] + Xtrain['age_65']
Xtrain['Age_old'] = Xtrain['age_75'] + Xtrain['age_85'] + Xtrain['age_MISS']
Xtest['Age_young'] = Xtest['age_05'] + Xtest['age_15'] + Xtrain['age_25'] + Xtrain['age_35'] 
+ Xtrain['age_45'] + Xtrain['age_55'] + Xtrain['age_65']
Xtest['Age_old'] = Xtest['age_75'] + Xtest['age_85'] + Xtrain['age_MISS']

In [247]:
Xtrain.head()

,MemberID,Year,ClaimsTruncated,DaysInHospital,age_05,age_15,age_25,age_35,age_45,age_55,...,DrugCountMean,DrugCount,labCount_min,labCount_max,labCount_ave,labcount_months,labNull,drugNull,Age_young,Age_old
0,210,Y1,0,0,0,0,0,1,0,0,...,1.666667,3.0,2.0,2.0,2.0,1.0,0,0,1,0
1,3197,Y1,0,0,1,0,0,0,0,0,...,1.250000,4.0,0.0,0.0,0.0,0.0,0,0,1,0
2,3889,Y1,0,0,0,0,0,0,0,0,...,3.000000,10.0,10.0,10.0,10.0,1.0,0,0,0,1
3,4187,Y1,0,0,0,0,0,0,0,1,...,6.100000,10.0,0.0,0.0,0.0,0.0,0,0,1,0
4,9063,Y1,0,0,0,0,0,0,0,0,...,1.000000,2.0,0.0,0.0,0.0,0.0,0,0,1,0

In [0]:
Xtrain['AdmissionRiskL70']=5*((Xtrain['pcg22']>0).astype(int))\
+((Xtrain['pcg32']>0).astype(int))+((Xtrain['pcg3']>0).astype(int))+3*((Xtrain['pcg44']>0).astype(int))\
+3*((Xtrain['pcg24']>0).astype(int))+4*((Xtrain['pcg37']>0).astype(int))+3*((Xtrain['pcg38']>0).astype(int))+5*((Xtrain['pcg26']>0).astype(int))\
+5*((Xtrain['pcg17']>0).astype(int))+((Xtrain['pcg39']>0).astype(int))+((Xtrain['pcg18']>0).astype(int))+4*((Xtrain['pcg8']>0).astype(int))\
+3*((Xtrain['pcg20']>0).astype(int))+((Xtrain['pcg21']>0).astype(int))\
+4*((Xtrain['pcg31']>0).astype(int))
+4*((Xtrain['pcg11']>0).astype(int))+((Xtrain['pcg29']>0).astype(int))+3*((Xtrain['pcg30']>0).astype(int))\
+(Xtrain['pcg23']>0).astype(int)+(Xtrain['pcg9']>0).astype(int)+3*(Xtrain['pcg41']>0).astype(int)+3*(Xtrain['pcg28']>0).astype(int)\
+((Xtrain['pcg2']>0).astype(int))+2*((Xtrain['pcg5']>0).astype(int))+((Xtrain['pcg33']>0).astype(int))\
+((Xtrain['pcg14']>0).astype(int))+((Xtrain['pcg1']>0).astype(int))+2*((Xtrain['pcg4']>0).astype(int))+((Xtrain['pcg15']>0).astype(int))\
+((Xtrain['pcg45']>0).astype(int))+4*((Xtrain['pcg36']>0).astype(int))+2*((Xtrain['pcg42']>0)).astype(int)\
+((Xtrain['pcg19']>0).astype(int))+((Xtrain['pcg27']>0).astype(int))+(2*(Xtrain['pcg43']>0).astype(int))+4*((Xtrain['pcg34']>0).astype(int))\
+2*(Xtrain['pcg12']>0).astype(int)+(Xtrain['pcg5']>0).astype(int)+3*(Xtrain['pcg13']>0).astype(int)\
+2*((Xtrain['pcg25']>0).astype(int))+2*((Xtrain['pcg40']>0).astype(int))+2*((Xtrain['pcg7']>0).astype(int))\
+5*((Xtrain['pcg35']>0).astype(int))+((Xtrain['pcg10']>0).astype(int))+((Xtrain['pcg16']>0).astype(int))

Xtrain['AdmissionRiskG70']=5*((Xtrain['pcg22']>0).astype(int))\
+((Xtrain['pcg32']>0).astype(int))+2*((Xtrain['pcg3']>0).astype(int))+4*((Xtrain['pcg44']>0).astype(int))\
+4*((Xtrain['pcg24']>0).astype(int))+3*((Xtrain['pcg37']>0).astype(int))+4*((Xtrain['pcg38']>0).astype(int))+5*((Xtrain['pcg26']>0).astype(int))\
+5*((Xtrain['pcg17']>0).astype(int))+((Xtrain['pcg39']>0).astype(int))+((Xtrain['pcg18']>0).astype(int))+3*((Xtrain['pcg8']>0).astype(int))\
+2*((Xtrain['pcg20']>0).astype(int))+((Xtrain['pcg21']>0).astype(int))\
+3*((Xtrain['pcg31']>0).astype(int))
+3*((Xtrain['pcg11']>0).astype(int))+2*((Xtrain['pcg29']>0).astype(int))+2*((Xtrain['pcg30']>0).astype(int))\
+4*(Xtrain['pcg23']>0).astype(int)+(Xtrain['pcg9']>0).astype(int)+3*(Xtrain['pcg41']>0).astype(int)+4*(Xtrain['pcg28']>0).astype(int)\
+((Xtrain['pcg2']>0).astype(int))+3*((Xtrain['pcg5']>0).astype(int))+((Xtrain['pcg33']>0).astype(int))\
+((Xtrain['pcg14']>0).astype(int))+((Xtrain['pcg1']>0).astype(int))+((Xtrain['pcg4']>0).astype(int))+((Xtrain['pcg15']>0).astype(int))\
+((Xtrain['pcg45']>0).astype(int))+5*((Xtrain['pcg36']>0).astype(int))+3*((Xtrain['pcg42']>0)).astype(int)\
+2*((Xtrain['pcg19']>0).astype(int))+((Xtrain['pcg27']>0).astype(int))+(3*(Xtrain['pcg43']>0).astype(int))+3*((Xtrain['pcg34']>0).astype(int))\
+2*(Xtrain['pcg12']>0).astype(int)+(Xtrain['pcg5']>0).astype(int)+4*(Xtrain['pcg13']>0).astype(int)\
+2*((Xtrain['pcg25']>0).astype(int))+5*((Xtrain['pcg40']>0).astype(int))+((Xtrain['pcg7']>0).astype(int))\
+5*((Xtrain['pcg35']>0).astype(int))+2*((Xtrain['pcg10']>0).astype(int))+2*((Xtrain['pcg16']>0).astype(int))
## 
Xtrain['AdmissionRisk']=Xtrain['AdmissionRiskL70']*Xtrain['Age_young']+Xtrain['AdmissionRiskG70']*Xtrain['Age_old']

In [0]:
Xtest['AdmissionRiskL70']=5*((Xtest['pcg22']>0).astype(int))\
+((Xtest['pcg32']>0).astype(int))+((Xtest['pcg3']>0).astype(int))+3*((Xtest['pcg44']>0).astype(int))\
+3*((Xtest['pcg24']>0).astype(int))+4*((Xtest['pcg37']>0).astype(int))+3*((Xtest['pcg38']>0).astype(int))+5*((Xtest['pcg26']>0).astype(int))\
+5*((Xtest['pcg17']>0).astype(int))+((Xtest['pcg39']>0).astype(int))+((Xtest['pcg18']>0).astype(int))+4*((Xtest['pcg8']>0).astype(int))\
+3*((Xtest['pcg20']>0).astype(int))+((Xtest['pcg21']>0).astype(int))\
+4*((Xtest['pcg31']>0).astype(int))
+4*((Xtest['pcg11']>0).astype(int))+((Xtest['pcg29']>0).astype(int))+3*((Xtest['pcg30']>0).astype(int))\
+(Xtest['pcg23']>0).astype(int)+(Xtrain['pcg9']>0).astype(int)+3*(Xtest['pcg41']>0).astype(int)+3*(Xtest['pcg28']>0).astype(int)\
+((Xtest['pcg2']>0).astype(int))+2*((Xtest['pcg5']>0).astype(int))+((Xtest['pcg33']>0).astype(int))\
+((Xtest['pcg14']>0).astype(int))+((Xtest['pcg1']>0).astype(int))+2*((Xtest['pcg4']>0).astype(int))+((Xtest['pcg15']>0).astype(int))\
+((Xtest['pcg45']>0).astype(int))+4*((Xtest['pcg36']>0).astype(int))+2*((Xtest['pcg42']>0)).astype(int)\
+((Xtest['pcg19']>0).astype(int))+((Xtest['pcg27']>0).astype(int))+(2*(Xtest['pcg43']>0).astype(int))+4*((Xtest['pcg34']>0).astype(int))\
+2*(Xtest['pcg12']>0).astype(int)+(Xtrain['pcg5']>0).astype(int)+3*(Xtrain['pcg13']>0).astype(int)\
+2*((Xtest['pcg25']>0).astype(int))+2*((Xtest['pcg40']>0).astype(int))+2*((Xtest['pcg7']>0).astype(int))\
+5*((Xtest['pcg35']>0).astype(int))+((Xtest['pcg10']>0).astype(int))+((Xtest['pcg16']>0).astype(int))

Xtest['AdmissionRiskG70']=5*((Xtest['pcg22']>0).astype(int))\
+((Xtest['pcg32']>0).astype(int))+2*((Xtest['pcg3']>0).astype(int))+4*((Xtest['pcg44']>0).astype(int))\
+4*((Xtest['pcg24']>0).astype(int))+3*((Xtest['pcg37']>0).astype(int))+4*((Xtest['pcg38']>0).astype(int))+5*((Xtest['pcg26']>0).astype(int))\
+5*((Xtest['pcg17']>0).astype(int))+((Xtest['pcg39']>0).astype(int))+((Xtest['pcg18']>0).astype(int))+3*((Xtrain['pcg8']>0).astype(int))\
+2*((Xtest['pcg20']>0).astype(int))+((Xtest['pcg21']>0).astype(int))\
+3*((Xtest['pcg31']>0).astype(int))
+3*((Xtest['pcg11']>0).astype(int))+2*((Xtest['pcg29']>0).astype(int))+2*((Xtest['pcg30']>0).astype(int))\
+4*(Xtest['pcg23']>0).astype(int)+(Xtest['pcg9']>0).astype(int)+3*(Xtest['pcg41']>0).astype(int)+4*(Xtest['pcg28']>0).astype(int)\
+((Xtest['pcg2']>0).astype(int))+3*((Xtest['pcg5']>0).astype(int))+((Xtest['pcg33']>0).astype(int))\
+((Xtest['pcg14']>0).astype(int))+((Xtest['pcg1']>0).astype(int))+((Xtest['pcg4']>0).astype(int))+((Xtest['pcg15']>0).astype(int))\
+((Xtest['pcg45']>0).astype(int))+5*((Xtest['pcg36']>0).astype(int))+3*((Xtest['pcg42']>0)).astype(int)\
+2*((Xtest['pcg19']>0).astype(int))+((Xtest['pcg27']>0).astype(int))+(3*(Xtest['pcg43']>0).astype(int))+3*((Xtest['pcg34']>0).astype(int))\
+2*(Xtest['pcg12']>0).astype(int)+(Xtest['pcg5']>0).astype(int)+4*(Xtest['pcg13']>0).astype(int)\
+2*((Xtest['pcg25']>0).astype(int))+5*((Xtest['pcg40']>0).astype(int))+((Xtest['pcg7']>0).astype(int))\
+5*((Xtest['pcg35']>0).astype(int))+2*((Xtest['pcg10']>0).astype(int))+2*((Xtest['pcg16']>0).astype(int))
## 
Xtest['AdmissionRisk']=Xtest['AdmissionRiskL70']*Xtest['Age_young']+Xtest['AdmissionRiskG70']*Xtest['Age_young']

In [250]:
Xtrain.head()

,MemberID,Year,ClaimsTruncated,DaysInHospital,age_05,age_15,age_25,age_35,age_45,age_55,...,labCount_max,labCount_ave,labcount_months,labNull,drugNull,Age_young,Age_old,AdmissionRiskL70,AdmissionRiskG70,AdmissionRisk
0,210,Y1,0,0,0,0,0,1,0,0,...,2.0,2.0,1.0,0,0,1,0,4,3,4
1,3197,Y1,0,0,1,0,0,0,0,0,...,0.0,0.0,0.0,0,0,1,0,4,3,4
2,3889,Y1,0,0,0,0,0,0,0,0,...,10.0,10.0,1.0,0,0,0,1,0,0,0
3,4187,Y1,0,0,0,0,0,0,0,1,...,0.0,0.0,0.0,0,0,1,0,1,2,1
4,9063,Y1,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,1,0,1,2,1

In [0]:
Xtrain.drop(['Age_old','Age_young','AdmissionRiskL70','AdmissionRiskG70'],axis=1, inplace=True)
Xtest.drop(['Age_old','Age_young','AdmissionRiskL70','AdmissionRiskG70'],axis=1, inplace=True)

In [253]:
Xtest.head()

,MemberID,Year,ClaimsTruncated,DaysInHospital,age_05,age_15,age_25,age_35,age_45,age_55,...,DrugCountMax,DrugCountMean,DrugCount,labCount_min,labCount_max,labCount_ave,labcount_months,labNull,drugNull,AdmissionRisk
0,4,Y2,0,0,1,0,0,0,0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0.0
1,210,Y2,0,0,0,0,0,1,0,0,...,0.0,0.00,0.0,1.0,1.0,1.0,1.0,0,0,0.0
2,3197,Y2,0,0,1,0,0,0,0,0,...,2.0,1.50,2.0,2.0,2.0,2.0,1.0,0,0,0.0
3,3457,Y2,0,0,1,0,0,0,0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0.0
4,3713,Y2,0,0,0,0,0,0,1,0,...,6.0,4.25,4.0,1.0,8.0,4.5,2.0,0,0,3.0

In [254]:
Xtrain.to_csv("drive/My Drive/Colab Notebooks/Data/train_data_AdRisk_hhp1.csv", encoding='utf-8')
Xtest.to_csv("drive/My Drive/Colab NotebooksData/test_data_AdRisk_hhp1.csv", encoding='utf-8')

FileNotFoundError: ignored